### ISSUE TITLE
”csmith -s 1283564260“ failed of FactPointTo.cpp:734:  Assertion `exist_fact' failed.

### ISSUE THREAD

**Issue by Hanseltu** [csmith-project/csmith#108] opened 2020-11-29 03:44 UTC
Hi.  I meet an assertion failed while using Csmith. Thanks.

```
$ csmith -s 1283564260
/*
 * This is a RANDOMLY GENERATED PROGRAM.
 *
 * Generator: csmith 2.4.0
 * Git version: 72c49db
 * Options:   -s 1283564260
 * Seed:      1283564260
 */

#include "csmith.h"


static long __undefined;

csmith: csmith/src/FactPointTo.cpp:734: static std::vector<const Variable*> FactPointTo::merge_pointees_of_pointers(const std::vector<const Variable*>&, const std::vector<const Fact*>&): Assertion `exist_fact' failed.
Aborted (core dumped)
```

**Comment by orestisfl** [comment] 2021-01-20 15:34
Also fails with `-s 2185594774` for me

**Comment by jxyang** [comment] 2021-01-21 14:39
Thanks for reporting. Confirmed.

**Comment by jxyang** [comment] 2021-01-25 00:30
The root cause is that when a parameters is an union containing pointers, the pointer analysis blindly assumes all pointer fields are valid in the context of the callee function. In this case, the pointer analysis should take dependence on union field analysis, and only produce a points-to fact for the pointer field that was last written.

Let me see if we can modify the points-to analysis to accommodate this special case. If not trivial, I'd move to disable pointer fields in unions, which haven't lead to many uncovered compiler bugs in the past anyway. Correct me if I am wrong.

**Comment by jxyang** [comment] 2021-01-25 01:11
Ok, pointers are removed from union fields. This should simplify points-to analysis quite a lot.

Let me know if you have a compelling reason to keep pointers inside unions.

Fixed by https://github.com/csmith-project/csmith/commit/0a69f2df476c09da98f92b9bfe9ab60444304366

**Closed by jxyang** 2021-01-25 01:11 UTC
